# Generated by Django 5.2.9 on 2025-12-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="image.png", upload_to=""),
        ),
    ]
